# Generated by Django 6.0 on 2026-01-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('nation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('matches_played', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('minutes_played', models.FloatField(blank=True, null=True)),
                ('goals', models.FloatField(default=0.0)),
                ('assists', models.FloatField(default=0.0)),
                ('penalties_scored', models.FloatField(default=0.0)),
                ('yellow_cards', models.FloatField(default=0.0)),
                ('red_cards', models.FloatField(default=0.0)),
                ('expected_goals', models.FloatField(default=0.0)),
                ('expected_assists', models.FloatField(default=0.0)),
                ('team_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'player_statistics',
            },
        ),
    ]
